M48
; DRILL file {KiCad 7.0.7} date Sat Nov  4 17:46:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-04T17:46:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0402
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0590
%
G90
G05
T1
X6.9Y-3.205
X6.9Y-3.305
X6.9Y-3.405
X6.9Y-3.505
T2
X4.76Y-2.675
X4.76Y-3.175
T3
X6.9Y-2.605
X6.9Y-2.905
T4
X4.355Y-2.7102
X4.355Y-3.6
T0
M30
