M48
; DRILL file {KiCad 8.0.6} date 2024-12-05T00:05:20-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-05T00:05:20-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0402
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0590
%
G90
G05
T1
X6.2795Y-2.5
T2
X6.9Y-2.605
X6.9Y-2.905
T3
X6.9Y-3.205
X6.9Y-3.305
X6.9Y-3.405
X6.9Y-3.505
T4
X4.76Y-2.675
X4.76Y-3.175
T5
X4.3701Y-2.701
X4.3701Y-2.8388
X4.3701Y-3.453
X4.3701Y-3.5908
M30
